/**
 * Ultimate-owned adaptation of PrimeNG's `DrawerStyle` (see
 * `.vendor-extracted/ng/drawer/drawer.ts` / `style/drawerstyle.ts`), shaped
 * to match `UBaseComponent`'s `styleModule: {css, classes}` contract. No
 * `@ultimate/uix-styles/drawer` entry exists yet, so `css`/`classes` are
 * authored locally (same precedent as `tieredMenuStyleModule`).
 * GAP-064 G3-D: `css` is the Aura structural port generated by `packages/themes/test/utils/g3d-port.mjs` (Spec §5–§8).
 */
const css = /*css*/ `
.u-drawer{display: flex;flex-direction: column;transform: translate3d(0px, 0px, 0px);position: relative;transition: transform 0.3s;background: dt('drawer.background');color: dt('drawer.color');border-style: solid;border-color: dt('drawer.border.color');box-shadow: dt('drawer.shadow');}
.u-drawer-content{overflow-y: auto;flex-grow: 1;padding: dt('drawer.content.padding');}
.u-drawer-header{display: flex;align-items: center;justify-content: space-between;flex-shrink: 0;padding: dt('drawer.header.padding');}
.u-drawer-footer{padding: dt('drawer.footer.padding');}
.u-drawer-title{font-weight: dt('drawer.title.font.weight');font-size: dt('drawer.title.font.size');}
.u-drawer.u-drawer-position-full{transition: none;transform: none;width: 100vw !important;height: 100vh !important;max-height: 100%;top: 0px !important;left: 0px !important;border-width: 1px;}
.u-drawer.u-drawer-position-left{width: 20rem;height: 100%;border-inline-end-width: 1px;}
.u-drawer.u-drawer-position-right{width: 20rem;height: 100%;border-inline-start-width: 1px;}
.u-drawer.u-drawer-position-top{height: 10rem;width: 100%;border-block-end-width: 1px;}
.u-drawer.u-drawer-position-bottom{height: 10rem;width: 100%;border-block-start-width: 1px;}
.u-drawer.u-drawer-position-left .u-drawer-content, .u-drawer.u-drawer-position-right .u-drawer-content, .u-drawer.u-drawer-position-top .u-drawer-content, .u-drawer.u-drawer-position-bottom .u-drawer-content{width: 100%;height: 100%;}
.u-drawer-mask:dir(rtl){flex-direction: row-reverse;}
.u-drawer-mask{position: fixed;inset: 0;display: flex;}
.u-drawer-position-right{margin-left: auto;}
.u-drawer-position-bottom{margin-top: auto;}
.u-drawer > [ufocustrap]{display: flex;flex-direction: column;flex: 1 1 auto;min-height: 0;}
`;

/** Params `UDrawer` passes into `cx('root'|'mask', params)`. */
export interface DrawerClassesParams {
  position?: "left" | "right" | "top" | "bottom" | "full";
}

const classes = {
  mask: () => ["u-drawer-mask"],
  root: (params: DrawerClassesParams = {}) => {
    const { position = "left" } = params;
    return ["u-drawer u-component", `u-drawer-position-${position}`];
  },
  header: "u-drawer-header",
  title: "u-drawer-title",
  pcCloseButton: "u-drawer-close-button",
  content: "u-drawer-content",
  footer: "u-drawer-footer",
};

/** `UBaseComponent`-shaped style module for `UDrawer`. */
export const drawerStyleModule = { css, classes };
