export { SCHEMA_VERSION } from "./version";
export type { ComponentIdentity } from "./identity";
export type { PropFact, EventFact, FrameworkApi, ComponentApi } from "./api";
export type { AccessibilityFacts } from "./accessibility";
export type { StyleIdentity } from "./style";
export type { Relationships } from "./relationships";
export type { ProvenanceRef } from "./provenance-ref";
export type { Guidance } from "./guidance";
export type { ComponentMetadata } from "./component-metadata";
export { nextMetadataVersion } from "./metadata-version";
export { validateComponentMetadata } from "./validate";
export type { ValidationResult } from "./validate";
