import type { StyleModule } from "@ultimate/vue-core";

/**
 * Ultimate-owned adaptation of PrimeVue's `SpeedDialStyle` (see
 * `.vendor-extracted/vue/speeddial/style/SpeedDialStyle.js`), shaped to
 * match `createBaseComponent`'s `styleModule: {css, classes}` contract.
 * No `@ultimate/uix-styles/speed-dial` entry exists yet, so `css`/
 * `classes` are authored locally (same precedent as this same
 * capability's Angular `speed-dial-style.ts` sibling).
 * GAP-064 G3-D: `css` is the Aura structural port generated by `packages/themes/test/utils/g3d-port.mjs` (Spec §5–§8).
 */
const css = /*css*/ `
.u-speeddial-mask{background: dt('mask.background');color: dt('mask.color');position: fixed;top: 0;left: 0;width: 100%;height: 100%;}
.u-speeddial-button:disabled, .u-speeddial-button:disabled *, .u-speeddial-action:disabled, .u-speeddial-action:disabled *{cursor: default;pointer-events: none;user-select: none;}
.u-speeddial-button:disabled, .u-speeddial-action:disabled{opacity: dt('disabled.opacity');}
.u-speeddial{position: static;display: flex;gap: dt('speeddial.gap');}
.u-speeddial-button{z-index: 1;}
.u-speeddial-list{margin: 0;padding: 0;list-style: none;display: flex;align-items: center;justify-content: center;transition: inset-block-start 0s linear dt('speeddial.transition.duration');pointer-events: none;outline: 0 none;z-index: 2;gap: dt('speeddial.gap');}
.u-speeddial-item{transform: scale(0);opacity: 0;transition: transform 200ms cubic-bezier(0.4, 0, 0.2, 1) 0ms, opacity 0.8s;will-change: transform;}
.u-speeddial-mask{position: absolute;border-radius: dt('content.border.radius');}
.u-speeddial:has(> .u-speeddial-button.u-speeddial-open) .u-speeddial-list{pointer-events: auto;}
.u-speeddial:has(> .u-speeddial-button.u-speeddial-open) .u-speeddial-item{transform: scale(1);opacity: 1;}
.u-speeddial-direction-up{flex-direction: column-reverse;align-items: center;}
.u-speeddial-direction-down{flex-direction: column;align-items: center;}
.u-speeddial-direction-left{flex-direction: row-reverse;justify-content: center;}
.u-speeddial-direction-right{flex-direction: row;justify-content: center;}
.u-speeddial-action{display: flex;align-items: center;justify-content: center;border-radius: 50%;cursor: pointer;width: 2.5rem;height: 2.5rem;}
.u-speeddial-item-hidden{visibility: hidden;}
`;

const classes = {
  root: (params: Record<string, unknown> = {}) => [
    "u-speeddial u-component",
    `u-speeddial-direction-${params.direction ?? "up"}`,
  ],
  pcButton: (params: Record<string, unknown> = {}) => ["u-speeddial-button", { "u-speeddial-open": Boolean(params.open) }],
  list: "u-speeddial-list",
  item: (params: Record<string, unknown> = {}) => ["u-speeddial-item", { "u-speeddial-item-hidden": Boolean(params.hidden) }],
  pcAction: "u-speeddial-action",
  actionIcon: "u-speeddial-action-icon",
  mask: "u-speeddial-mask",
};

export const speedDialStyleModule: StyleModule = { css, classes };
