/**
 * Ultimate-owned adaptation of PrimeNG's `ConfirmPopupStyle` (see
 * `.vendor-extracted/ng/confirmpopup/confirmpopup.ts` / `style/`), shaped
 * to match `UBaseComponent`'s `styleModule: {css, classes}` contract. No
 * `@ultimate/uix-styles/confirm-popup` entry exists yet, so `css`/`classes`
 * are authored locally (same precedent as `tieredMenuStyleModule`).
 * GAP-064 G3-D: `css` is the Aura structural port generated by `packages/themes/test/utils/g3d-port.mjs` (Spec §5–§8).
 */
const css = /*css*/ `
.u-confirmpopup{position: absolute;margin-top: dt('confirmpopup.gutter');top: 0;left: 0;background: dt('confirmpopup.background');color: dt('confirmpopup.color');border: 1px solid dt('confirmpopup.border.color');border-radius: dt('confirmpopup.border.radius');box-shadow: dt('confirmpopup.shadow');will-change: transform;}
.u-confirmpopup-content{display: flex;align-items: center;padding: dt('confirmpopup.content.padding');gap: dt('confirmpopup.content.gap');}
.u-confirmpopup-icon{font-size: dt('confirmpopup.icon.size');width: dt('confirmpopup.icon.size');height: dt('confirmpopup.icon.size');color: dt('confirmpopup.icon.color');}
.u-confirmpopup-footer{display: flex;justify-content: flex-end;gap: dt('confirmpopup.footer.gap');padding: dt('confirmpopup.footer.padding');}
.u-confirmpopup-footer button{width: auto;}
.u-confirmpopup-footer button:last-child{margin: 0;}
`;

const classes = {
  root: () => ["u-confirmpopup u-component"],
  content: "u-confirmpopup-content",
  icon: "u-confirmpopup-icon",
  message: "u-confirmpopup-message",
  footer: "u-confirmpopup-footer",
};

/** `UBaseComponent`-shaped style module for `UConfirmPopup`. */
export const confirmPopupStyleModule = { css, classes };
