import { defineConfig } from "tsup";

export default defineConfig({
  entry: {
    index: "src/index.ts",
    "button/index": "src/button/index.ts",
    "checkbox/index": "src/checkbox/index.ts",
    "dialog/index": "src/dialog/index.ts",
    "menu/index": "src/menu/index.ts",
    "paginator/index": "src/paginator/index.ts",
    "scroller/index": "src/scroller/index.ts",
    "table/index": "src/table/index.ts",
    "tooltip/index": "src/tooltip/index.ts",
    "accordion/index": "src/accordion/index.ts",
    "autocomplete/index": "src/autocomplete/index.ts",
    "avatar/index": "src/avatar/index.ts",
    "avatar-group/index": "src/avatar-group/index.ts",
    "block-ui/index": "src/block-ui/index.ts",
    "breadcrumb/index": "src/breadcrumb/index.ts",
    "button-group/index": "src/button-group/index.ts",
    "card/index": "src/card/index.ts",
    "carousel/index": "src/carousel/index.ts",
    "cascade-select/index": "src/cascade-select/index.ts",
    "chip/index": "src/chip/index.ts",
    "color-picker/index": "src/color-picker/index.ts",
    "confirm-dialog/index": "src/confirm-dialog/index.ts",
    "confirm-popup/index": "src/confirm-popup/index.ts",
    "context-menu/index": "src/context-menu/index.ts",
    "data-scroller/index": "src/data-scroller/index.ts",
    "data-view/index": "src/data-view/index.ts",
    "date-picker/index": "src/date-picker/index.ts",
    "deferred-content/index": "src/deferred-content/index.ts",
    "divider/index": "src/divider/index.ts",
    "dock/index": "src/dock/index.ts",
    "drawer/index": "src/drawer/index.ts",
    "fieldset/index": "src/fieldset/index.ts",
    "file-upload/index": "src/file-upload/index.ts",
    "float-label/index": "src/float-label/index.ts",
    "galleria/index": "src/galleria/index.ts",
    "icon-field/index": "src/icon-field/index.ts",
    "image/index": "src/image/index.ts",
    "inplace/index": "src/inplace/index.ts",
    "input-chips/index": "src/input-chips/index.ts",
    "input-mask/index": "src/input-mask/index.ts",
    "input-number/index": "src/input-number/index.ts",
    "input-otp/index": "src/input-otp/index.ts",
    "input-switch/index": "src/input-switch/index.ts",
    "input-text/index": "src/input-text/index.ts",
    "input-textarea/index": "src/input-textarea/index.ts",
    "key-filter/index": "src/key-filter/index.ts",
    "knob/index": "src/knob/index.ts",
    "listbox/index": "src/listbox/index.ts",
    "mega-menu/index": "src/mega-menu/index.ts",
    "mention/index": "src/mention/index.ts",
    "menubar/index": "src/menubar/index.ts",
    "message/index": "src/message/index.ts",
    "meter-group/index": "src/meter-group/index.ts",
    "multi-select/index": "src/multi-select/index.ts",
    "multi-state-checkbox/index": "src/multi-state-checkbox/index.ts",
    "order-list/index": "src/order-list/index.ts",
    "organization-chart/index": "src/organization-chart/index.ts",
    "panel/index": "src/panel/index.ts",
    "panel-menu/index": "src/panel-menu/index.ts",
    "password/index": "src/password/index.ts",
    "pick-list/index": "src/pick-list/index.ts",
    "popover/index": "src/popover/index.ts",
    "progress-bar/index": "src/progress-bar/index.ts",
    "progress-spinner/index": "src/progress-spinner/index.ts",
    "radio-button/index": "src/radio-button/index.ts",
    "rating/index": "src/rating/index.ts",
    "scroll-panel/index": "src/scroll-panel/index.ts",
    "scroll-top/index": "src/scroll-top/index.ts",
    "select/index": "src/select/index.ts",
    "select-button/index": "src/select-button/index.ts",
    "skeleton/index": "src/skeleton/index.ts",
    "slider/index": "src/slider/index.ts",
    "speed-dial/index": "src/speed-dial/index.ts",
    "split-button/index": "src/split-button/index.ts",
    "splitter/index": "src/splitter/index.ts",
    "stepper/index": "src/stepper/index.ts",
    "steps/index": "src/steps/index.ts",
    "style-class/index": "src/style-class/index.ts",
    "tabs/index": "src/tabs/index.ts",
    "tag/index": "src/tag/index.ts",
    "terminal/index": "src/terminal/index.ts",
    "tiered-menu/index": "src/tiered-menu/index.ts",
    "timeline/index": "src/timeline/index.ts",
    "toast/index": "src/toast/index.ts",
    "toggle-button/index": "src/toggle-button/index.ts",
    "toolbar/index": "src/toolbar/index.ts",
    "tri-state-checkbox/index": "src/tri-state-checkbox/index.ts",
  },
  format: ["esm"],
  outExtension: () => ({ js: ".mjs" }),
  // Declaration files are generated separately by `tsc` (see this package's
  // `build` script and `tsconfig.dts.json`), not by tsup's own `dts: true`
  // (which runs one rollup-plugin-dts program per entry and ran out of heap
  // once every component subpath became an entry). `tsc` emits correct
  // per-file `.d.ts` output in one program, the same approach
  // `packages/vue` uses.
  dts: false,
  sourcemap: true,
  clean: true,
  splitting: false,
  outDir: "dist",
});
