import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import { fileURLToPath } from "node:url";

/**
 * Builds only the browser (client-hydration) bundle. The HTML page shell is
 * generated by the Express server (server.ts) at request time, not by
 * Vite, so this config points directly at entry-client.tsx as a rollup
 * input rather than an index.html entry. Output lands under dist/client —
 * a separate, independently-inspectable artifact from the server build
 * (produced by scripts/build-server.mjs, this "build" script's second
 * sub-step) per AC3.1.
 */
export default defineConfig({
  plugins: [react()],
  build: {
    outDir: "dist/client",
    emptyOutDir: true,
    rollupOptions: {
      input: fileURLToPath(new URL("./src/entry-client.tsx", import.meta.url)),
      output: {
        // Fixed, predictable filename (no content hash) so the server's
        // static-asset route and its <script> tag reference stay in sync
        // without a manifest lookup — this is a verification harness, not
        // a CDN-fronted production deployment.
        entryFileNames: "entry-client.js",
      },
    },
  },
});
