/**
 * Ultimate-owned adaptation of PrimeVue's `PopoverStyle` (see
 * `.vendor-extracted/vue/popover/Popover.vue` / `BasePopover.vue`), shaped
 * to match `createBaseComponent`'s `styleModule: {css, classes}` contract.
 * No `@ultimate/uix-styles/popover` entry exists yet, so `css`/`classes`
 * are authored locally (same precedent as other Overlay-family components).
 * GAP-064 G3-D: `css` is the Aura structural port generated by `packages/themes/test/utils/g3d-port.mjs` (Spec §5–§8).
 */
const css = /*css*/ `
.u-popover{margin-block-start: dt('popover.gutter');background: dt('popover.background');color: dt('popover.color');border: 1px solid dt('popover.border.color');border-radius: dt('popover.border.radius');box-shadow: dt('popover.shadow');will-change: transform;}
.u-popover-content{padding: dt('popover.content.padding');}
.u-popover{position: absolute;}
.u-popover-content{position: relative;}
`;

const classes = {
  root: () => ["u-popover u-component"],
  content: "u-popover-content",
};

/** `createBaseComponent`-shaped style module for `UPopover`. */
export const popoverStyleModule = { css, classes };
