import type { StyleModule } from "@ultimate/vue-core";

/**
 * Ultimate-owned adaptation of PrimeVue's `SplitButtonStyle` (see
 * `.vendor-extracted/vue/splitbutton/style/SplitButtonStyle.js`), shaped
 * to match `createBaseComponent`'s `styleModule: {css, classes}` contract.
 * No `@ultimate/uix-styles/split-button` entry exists yet, so
 * `css`/`classes` are authored locally — same precedent as this same
 * capability's Angular/React `split-button-style.ts` siblings.
 * GAP-064 G3-D: `css` is the Aura structural port generated by `packages/themes/test/utils/g3d-port.mjs` (Spec §5–§8).
 */
const css = /*css*/ `
.u-splitbutton{display: inline-flex;position: relative;border-radius: dt('splitbutton.border.radius');}
.u-splitbutton-button.u-button{border-start-end-radius: 0;border-end-end-radius: 0;border-inline-end: 0 none;}
.u-splitbutton-button.u-button:focus-visible, .u-splitbutton-dropdown.u-button:focus-visible{z-index: 1;}
.u-splitbutton-button.u-button:not(:disabled):hover, .u-splitbutton-button.u-button:not(:disabled):active{border-inline-end: 0 none;}
.u-splitbutton-dropdown.u-button{border-start-start-radius: 0;border-end-start-radius: 0;}
`;

const classes = {
  root: "u-splitbutton u-component",
  pcButton: "u-splitbutton-button",
  pcDropdown: "u-splitbutton-dropdown",
};

export const splitButtonStyleModule: StyleModule = { css, classes };
