import { defineConfig } from "vite";
import vue from "@vitejs/plugin-vue";
import { fileURLToPath } from "node:url";

/**
 * One Vite config serving both sub-steps of the "build" script (see
 * package.json):
 *
 * 1. `vite build --outDir dist/client` (default, non-SSR) — the browser
 *    (client-hydration) bundle, entry-client.ts. The HTML page shell is
 *    generated by the Express server (server.js) at request time, not by
 *    Vite, so this points directly at entry-client.ts as a rollup input
 *    rather than an index.html entry.
 * 2. `vite build --outDir dist --ssr src/entry-server.ts` — the
 *    Node-runnable SSR bundle, compiling entry-server.ts's `.vue` imports
 *    (via @vitejs/plugin-vue, the same compiler both builds share) into
 *    plain JS. This is Vue's own documented production SSR build shape
 *    (vuejs.org/guide/scaling-up/ssr.html's "Higher Level Solutions" /
 *    Vite's own `build:server` example: `vite build --outDir dist/server
 *    --ssr src/entry-server.js`), adapted here to land directly at
 *    dist/entry-server.js (flat `--outDir dist`, matching what server.js's
 *    own `import("./entry-server.js")` and the "start" script's
 *    `node dist/server.js` expect).
 *
 * Both outputs are separate, independently-inspectable artifacts (dist/
 * client/** vs. dist/entry-server.js) per this harness's acceptance
 * criteria. `isSsrBuild` (Vite 5.4's documented conditional-config flag) is
 * compared explicitly against `true` per Vite's own recommendation, since
 * some config-loading tools pass `undefined` instead of `false`.
 */
export default defineConfig(({ isSsrBuild }) => {
  if (isSsrBuild === true) {
    // The SSR entry itself (src/entry-server.ts) and --outDir dist are
    // supplied by the "build" script's own CLI invocation
    // (`vite build --ssr src/entry-server.ts --outDir dist`), matching
    // Vite's own documented `build:server` script shape verbatim; only the
    // fixed output filename (avoiding a content-hashed name so server.js's
    // `import("./entry-server.js")` needs no manifest lookup) is set here.
    return {
      plugins: [vue()],
      build: {
        emptyOutDir: false,
        rollupOptions: {
          output: {
            entryFileNames: "entry-server.js",
          },
        },
      },
    };
  }

  return {
    plugins: [vue()],
    build: {
      outDir: "dist/client",
      emptyOutDir: true,
      rollupOptions: {
        input: fileURLToPath(new URL("./src/entry-client.ts", import.meta.url)),
        output: {
          // Fixed, predictable filename (no content hash) so the server's
          // static-asset route and its <script> tag reference stay in sync
          // without a manifest lookup — this is a verification harness, not
          // a CDN-fronted production deployment.
          entryFileNames: "entry-client.js",
        },
      },
    },
  };
});
