/**
 * Ultimate-owned adaptation of PrimeNG's `ConfirmDialogStyle` (see
 * `.vendor-extracted/ng/confirmdialog/confirmdialog.ts` / `style/`), shaped
 * to match `UBaseComponent`'s `styleModule: {css, classes}` contract. No
 * `@ultimate/uix-styles/confirm-dialog` entry exists yet, so `css`/`classes`
 * are authored locally (same precedent as `tieredMenuStyleModule`).
 * GAP-064 G3-D: `css` is the Aura structural port generated by `packages/themes/test/utils/g3d-port.mjs` (Spec §5–§8).
 */
const css = /*css*/ `
.u-dialog-content:has(> .u-confirmdialog-message){display: flex;align-items: center;gap: dt('confirmdialog.content.gap');}
.u-confirmdialog-icon{color: dt('confirmdialog.icon.color');font-size: dt('confirmdialog.icon.size');width: dt('confirmdialog.icon.size');height: dt('confirmdialog.icon.size');}
.u-confirmdialog-footer{display: flex;justify-content: flex-end;gap: 0.5rem;}
.u-confirmdialog-icon{flex-shrink: 0;}
.u-confirmdialog-message{flex-grow: 1;}
`;

const classes = {
  root: () => ["u-confirmdialog"],
  icon: "u-confirmdialog-icon",
  message: "u-confirmdialog-message",
  footer: "u-confirmdialog-footer",
};

/** `UBaseComponent`-shaped style module for `UConfirmDialog`. */
export const confirmDialogStyleModule = { css, classes };
